# Spring Boot configuration
spring:
  datasource:
    username: postgres
    password: 241201
    url: jdbc:postgresql://localhost:5432/weatherDB
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
  sql:
    init:
      mode: never
  api:
    url: https://api.weatherapi.com/v1/current.json?key=4418a8f90af74bf5a0d154951233006&q=Minsk&aqi=no
  scheduled:
    fixed:
      rate: 60000
    initial:
      delay: 0

